/** Column order from `isrctn_uk_cancer_trials_complete.xlsx`. */
export const UK_EXCEL_COLUMNS = [
  "ISRCTN",
  "DOI",
  "Integrated Research Application System (IRAS)",
  "Central Portfolio Management System (CPMS)",
  "Sponsor's protocol code number",
  "Sponsor",
  "Funders",
  "Submission date",
  "Recruitment status",
  "Overall study status",
  "Last edited",
  "Condition category",
  "Primary study design",
  "Allocation",
  "Masking",
  "Control",
  "Assignment",
  "Purpose",
  "Scientific title",
  "Study acronym",
  "Primary objective",
  "Secondary objectives",
  "Ethics approval(s)",
  "Health condition(s) or problem(s) studied",
  "Intervention",
  "Phase",
  "Drug /biological / vaccine name(s)",
  "Primary outcome measure(s)",
  "Key secondary outcome measure(s)",
  "Completion date",
  "Age group",
  "Target sample size at registration",
  "Key inclusion criteria",
  "Key exclusion criteria",
  "Countries of recruitment",
  "Study participating centre",
  "Results and Publications",
] as const
